Session/3 StatefulWidget のライフサイクル
oyuno-hito/flutter-training pull request #16
Opened 2023-12-01 06:35 UTC by oyuno-hito

## 課題

close #4 

## 対応箇所

- [x] [StatefulWidget](https://api.flutter.dev/flutter/widgets/StatefulWidget-class.html) を継承した Widget で構築された新しい画面を追加する
- [x] 新しい画面の背景色は Colors.green に設定する
- [x] アプリ起動時に新しい画面に遷移する
- [x] 新しい画面が表示されたら、0.5 秒後に前回まで作っていた画面に遷移する
- [x] 前回まで作っていた画面の Close ボタンをタップすると画面を閉じる

## 動作
- expected

https://github.com/yumemi-inc/flutter-training-template/blob/main/docs/sessions/images/lifecycle/demo.gif?raw=true

- actual(iOS)

https://github.com/oyuno-hito/flutter-training/assets/41560259/13fd55cd-dbdd-4c1a-a11a-cf2b45605c59

- actual(android)

https://github.com/oyuno-hito/flutter-training/assets/41560259/10888788-05d6-488a-b3d0-abd4a9878f41

2023-12-04 06:05 UTC, trm11tkr requested changes
ご対応いただきありがとうございます！
いくつかコメントさせていただきましたのでご確認お願いします！

2023-12-04 06:05 UTC, trm11tkr commented on lib/features/weather/screen/weather_screen.dart
> +                          },
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 

アロー構文で記述するともっとシンプルになり可読性も向上するかと思います！🤤
[FYI](https://dart.dev/language/functions#:~:text=For%20functions%20that%20contain%20just%20one%20expression%2C%20you%20can%20use%20a%20shorthand%20syntax%3A)
```suggestion
                          onPressed: () => Navigator.pop(context),
```

2023-12-04 06:05 UTC, trm11tkr commented on lib/main.dart
> +class MainApp extends StatelessWidget {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
StatelessWidget に戻すことを忘れておらず素敵です😍
Widget を切り出した際は元のコードを修正し忘れることがあるので注意していきましょう！

2023-12-04 06:05 UTC, trm11tkr commented on lib/main.dart
> +      home: const SplashScreen(),
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
> If the app only has one page, then you can specify it using home instead.

[routes property](https://api.flutter.dev/flutter/material/MaterialApp/routes.html)のドキュメントによると、`home`プロパティはアプリが１ページのみの場合に適していそうですね！
複数ページある場合は、`initialRoute`を設定してあげると良さそうです！
```suggestion
      initialRoute: Routes.splash.path,
```

2023-12-04 06:05 UTC, trm11tkr commented on lib/routes.dart
> +enum Routes {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
enum で定義してあげることで 安全性・保守性が高まっていますね😍

2023-12-04 06:05 UTC, trm11tkr commented on lib/features/splash/screen/splash_screen.dart
> +    await Navigator.pushNamed(context, '/weather');
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
保守性を高めるためにも 定義した `Routes` を使う方が適切そうです…！

```suggestion
    await Navigator.pushNamed(context, Routes.weather.path);
```

2023-12-04 07:09 UTC, oyuno-hito commented on lib/features/splash/screen/splash_screen.dart
> +    await Navigator.pushNamed(context, '/weather');
こちらで修正しました:pray:
[96727a1](https://github.com/oyuno-hito/flutter-training/pull/16/commits/96727a1ca74fcfab8819ee2d690b20e4be00bfca)

2023-12-04 07:09 UTC, oyuno-hito commented on lib/main.dart
> +      home: const SplashScreen(),
こちらで修正しました 🙏
[96727a1](https://github.com/oyuno-hito/flutter-training/pull/16/commits/96727a1ca74fcfab8819ee2d690b20e4be00bfca)

2023-12-04 07:10 UTC, oyuno-hito commented on lib/features/weather/screen/weather_screen.dart
> +                          },
こちらで修正しました 🙏 
[109688d](https://github.com/oyuno-hito/flutter-training/pull/16/commits/109688d59150f1b678a4f97bc566e00a0d7027f6)

2023-12-04 08:37 UTC, trm11tkr commented on lib/features/splash/screen/splash_screen.dart
> +    unawaited(
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
https://github.com/flutter/flutter/issues/120902#issuecomment-1434410353 で同じように警告に困っている人がいました。
今回の対応で問題なさそうですね🙆

2023-12-04 08:38 UTC, trm11tkr approved these changes
LGTM です！
ご対応いただきありがとうございました！

2023-12-05 09:04 UTC, oyuno-hito commented
レビューありがとうございます！マージします！

2023-12-05 09:04 UTC, merged