API のエラーハンドリング
oyuno-hito/flutter-training pull request #18
Opened 2023-12-06 10:06 UTC by oyuno-hito

## 課題

close #6 

## 対応箇所

- [x] 使用する API を fetchSimpleWeather() から fetchThrowsWeather() に変更する
- [x] API のエラーを補足して、エラーの内容に応じて [AlertDialog](https://api.flutter.dev/flutter/material/AlertDialog-class.html) でメッセージを表示する
- [x] [AlertDialog](https://api.flutter.dev/flutter/material/AlertDialog-class.html) の OK ボタンをタップすると、ダイアログを閉じる

レビュー表

- [x] エラーの内容によって、メッセージを分けているか
- [ ] freezed_annotation, freezed のコミットを一緒にまとめているか
- [x] クリックイベントをメソッドとして切り出しているか
- [x] Dialog をコンポーネントとして抽出しているか
- [ ] エラーハンドリングが[公式ドキュメント](https://dart.dev/effective-dart/usage#error-handling)に従っているか

## 動作

- expect

https://github.com/yumemi-inc/flutter-training-template/blob/main/docs/sessions/images/error/demo.gif?raw=true

- iOS

https://github.com/oyuno-hito/flutter-training/assets/41560259/4f4b998c-0d0a-4fc5-b269-06eee0effd1f

- android

https://github.com/oyuno-hito/flutter-training/assets/41560259/a6ef4aef-d3d0-40d9-9a37-d0a9f31d6f4d

2023-12-07 04:01 UTC, trm11tkr requested changes
いくつかコメントさせていただきましたのでご確認よろしくお願いします！

2023-12-07 04:01 UTC, trm11tkr commented on lib/features/weather/components/error_dialog.dart
> +class ErrorDialogWidget extends StatelessWidget {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
コンポーネント分割できていて素敵です😍
可読性・保守性が向上しましたね✨

2023-12-07 04:01 UTC, trm11tkr commented on lib/features/weather/screen/weather_screen.dart
> +    } on YumemiWeatherError catch (e) {
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
https://github.com/oyuno-hito/flutter-training/blob/cdaa78953abed41d37233729afa1a2ef76c9ef64/lib/features/weather/model/weather_condition.dart#L12
不正なレスポンスを受け取った場合に `Exception`をスローするように設計していただいているため、`Exception`もハンドリングできるようにしましょう！

これに伴い、showDialog を 2箇所で呼び出すことになると思いますが、ダイアログを表示をプライベートメソッドに切り出すことで可読性・保守性が向上しそうです！

```dart

  Future<void> _updateWeather() async {
    try {
      // 省略
    } on YumemiWeatherError catch (e) {
      _showDialog(e.convertErrorMessage());
    } on Exception catch (_) {
      _showDialog({適切な文言});
    }
  }

  void _showDialog(String message) {
    unawaited(
      showDialog<void>(
        context: context,
        barrierDismissible: false,
        builder: (_) {
          return ErrorDialogWidget(errorMessage: message);
        },
      ),
    );
  }
```

2023-12-07 04:01 UTC, trm11tkr commented on lib/features/weather/screen/weather_screen.dart
> +      await showDialog<void>(
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg) 
現状はダイアログから値を受け取らず、後続の処理もないので `unawaited`でラップする形が適していそうです！

2023-12-07 04:01 UTC, trm11tkr commented on lib/features/weather/components/error_dialog.dart
> +        GestureDetector(
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
[issue の 動作イメージ](https://github.com/oyuno-hito/flutter-training/issues/6) を見ると [TextButton](https://api.flutter.dev/flutter/material/TextButton-class.html)の方が適していそうかと思いました。
ただ、課題にはボタンの実装について触れていないのでどちらでも良いかもしれませんし、実際の案件でもデザイン次第ではありますね🤔

FYI:
- https://docs.flutter.dev/release/breaking-changes/buttons
- https://api.flutter.dev/flutter/widgets/GestureDetector-class.html

2023-12-07 06:58 UTC, oyuno-hito commented on lib/features/weather/components/error_dialog.dart
> +        GestureDetector(
こちらで修正しました！
[a77930a](https://github.com/oyuno-hito/flutter-training/pull/18/commits/a77930a55930c07c56f8c0b6ae7130343e9bc82f)

2023-12-07 06:59 UTC, oyuno-hito commented on lib/features/weather/screen/weather_screen.dart
> +      await showDialog<void>(
こちらで修正しました！
[e0c5190](https://github.com/oyuno-hito/flutter-training/pull/18/commits/e0c51908b2ae46c8196af325d764b6ac71bc0a26)

2023-12-07 07:00 UTC, oyuno-hito commented on lib/features/weather/screen/weather_screen.dart
> +    } on YumemiWeatherError catch (e) {
こちらでWeatherConditionでのExceptionをハンドリングする処理を追加し、階層の整理を行いました！
[741b0db](https://github.com/oyuno-hito/flutter-training/pull/18/commits/741b0db567aaf2aee3440456e3a3b4458e9bf057)

こちらでプライベートメソッドへの切り出しを行いました！
[373a232](https://github.com/oyuno-hito/flutter-training/pull/18/commits/373a2322b865b4a401c96d67dae531643141cd49)

2023-12-08 01:43 UTC, trm11tkr approved these changes
LGTM です！ご対応ありがとうございます！

2023-12-08 01:43 UTC, trm11tkr commented on lib/features/weather/exceptions/app_exception.dart
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
エラーを別ファイルに切り出したことで可読性・保守性が高まっていて素敵です🥰

2023-12-08 01:43 UTC, trm11tkr commented on lib/features/weather/model/weather_condition.dart
> +        orElse: () => throw const WeatherConditionException(),
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
😍

2023-12-19 07:05 UTC, oyuno-hito commented
レビューありがとうございました！マージします！

2023-12-19 07:05 UTC, merged