Session/10 Widget tests を書く
oyuno-hito/flutter-training pull request #24
Opened 2024-01-26 10:19 UTC by oyuno-hito

## 課題

close #11

## 対応箇所
- weather_test.dartで検証
  - [x] 特定の条件で、天気予報画面に晴れの画像が表示されること
  - [x] 特定の条件で、天気予報画面に曇りの画像が表示されること
  - [x] 特定の条件で、天気予報画面に雨の画像が表示されること
- degrees_test.dartで検証
  - [x] 特定の条件で、天気予報画面に最高気温が表示されること
  - [x] 特定の条件で、天気予報画面に最低気温が表示されること
- weather_screen_test.dartで検証
  - [x] 特定の条件で、天気予報画面にダイアログが表示され、特定のメッセージが表示されること

レビュー項目
-[x] テストの description が適切な表現になっているか
-[x] 効果的なテストコードか
-[ ] デバイスサイズ変更の意図をコメントしているか
  - 必要であれば追記しようと思います。
-[x] デバイスサイズ変更の後処理(tearDown)をしているか
-[x] コンポーネントで完結するテストに、画面遷移など他の要素を含めていないか
-[ ] 複数プラットフォームや複数スクリーンサイズをテストする時は TestVariant を活用しているか
  - 単一スクリーンサイズでの検証にとどめているため該当していないです

## 動作

テスト作成のみのため動作は変わらないです

2024-01-29 10:51 UTC, trm11tkr reviewed
ご対応いただきありがとうございます！
テストに関しては丁寧に実施していてとても良さそうでした！
細かな点でいくつかコメントさせていただきましたのでご確認よろしくお願いいたします。

2024-01-29 10:51 UTC, trm11tkr commented on analysis_options.yaml
> +    invalid_use_of_visible_for_testing_member: error
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
👍

2024-01-29 10:51 UTC, trm11tkr commented on test/features/weather/components/weather_test.dart
> +        final finder = findSvgImage('assets/sunny.svg');
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg) 
Finder class の [bySemanticsLabel](https://api.flutter.dev/flutter/flutter_test/CommonFinders/bySemanticsLabel.html) を活用するともっと簡単に Widget を見つけることができそうです！

FYI: https://qiita.com/KKusumi/items/f458a42bbbf1958ad8d1#findbysemanticslabel

2024-01-29 10:51 UTC, trm11tkr commented on test/features/weather/components/degrees_test.dart
> +    final defalutTemperatureFinder = find.text('** ℃');
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
```suggestion
    final defaultTemperatureFinder = find.text('** ℃');
```

2024-01-29 10:51 UTC, trm11tkr commented on test/features/weather/screen/weather_screen_test.dart
> +            // navigatorObservers: [mockNavigatorObserver],
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
不要なコメントは削除お願いします！

2024-01-29 10:51 UTC, trm11tkr commented on test/features/weather/screen/weather_screen_test.dart
> +              // navigatorObservers: [mockNavigatorObserver],
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
不要なコメントは削除お願いします！

2024-01-29 10:51 UTC, trm11tkr commented on test/features/weather/screen/weather_screen_test.dart
> +
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
こちらの改行は不要かと思われます…！

2024-01-29 10:51 UTC, trm11tkr commented on test/features/weather/screen/weather_screen_test.dart
> +        await widgetTester.pumpWidget(
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
現状作成していただいている `pumpWidget` 関数を修正することでこちらも関数に切り出すことができそうです！

![imo-badge](https://img.shields.io/badge/review-imo-orange.svg) 
他の箇所で作成していただいている `pumpWidget` 関数も同様ですが、何の Widget を pump しているかがわかるような命名だと可読性が向上しそうです！ex) `pumpWeatherScreen`, `pumpErrorDialogWidget` 
```dart
Future<void> pumpWeatherScreen(
    WidgetTester widgetTester, {
    List<Override> overrides = const [],
  }) async {
    await widgetTester.pumpWidget(
      ProviderScope(
        overrides: overrides,
        child: MaterialApp(
          home: const WeatherScreen(),
          navigatorObservers: [mockNavigatorObserver],
        ),
      ),
    );
  }
```

2024-01-29 10:51 UTC, trm11tkr commented on test/features/weather/components/error_dialog_test.dart
> +    await widgetTester.pumpAndSettle();
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
Widget の存在による検証をしていないのでこちらは [widgetTester.pump()](https://api.flutter.dev/flutter/flutter_test/WidgetTester/pump.html)で良さそうに思いました

2024-01-29 10:51 UTC, trm11tkr commented on test/features/weather/screen/weather_screen_test.dart
> +    expect(weatherScreenFinder, findsNothing);
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
こちらも `verify(mockNavigatorObserver.didPop(any, any)).called(1);`による検証で良さそうに思いましたが、何か意図があり現状の方法で検証をされていますでしょうか？

2024-01-29 10:51 UTC, trm11tkr commented on test/features/weather/screen/weather_screen_test.dart
> +      await widgetTester.pumpAndSettle();
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
他の箇所も同様ですが、`pump`ではなく、`pumpAndSettle`をしているのはなぜでしょうか？？

特に意図がなければ`pump`で良さそうに思いました…！

2024-01-30 10:12 UTC, oyuno-hito commented on test/features/weather/components/degrees_test.dart
> +    final defalutTemperatureFinder = find.text('** ℃');
こちらで修正しました
[6ffdef9](https://github.com/oyuno-hito/flutter-training/pull/24/commits/6ffdef9af3873d7d886696363164f5946802cda3)

2024-01-30 10:14 UTC, oyuno-hito commented on test/features/weather/components/weather_test.dart
> +        final finder = findSvgImage('assets/sunny.svg');
良さげですね！修正しました！
[06ae6fc](https://github.com/oyuno-hito/flutter-training/pull/24/commits/06ae6fcbf2e952beed9bfab4f57f316f1665f44e)

合わせて別コミットでパラメタライズドテストを実施するように修正してみています！こちらもレビューいただければと思います 🙏 (当初はforEachを利用しようとしていたのですがforを使うべきというハイライトが出たため修正してテストを書いています。違和感...)
[014ca60](https://github.com/oyuno-hito/flutter-training/pull/24/commits/014ca6097cecdb32d7b696858bf24ba92ff2050a)

2024-01-30 10:14 UTC, oyuno-hito commented on test/features/weather/screen/weather_screen_test.dart
> +              // navigatorObservers: [mockNavigatorObserver],
こちらで修正ました
[不要なコメントと改行の削除](https://github.com/oyuno-hito/flutter-training/pull/24/commits/818c0c4bfefbc5400056e1f60605e514494d19a2)

2024-01-30 10:14 UTC, oyuno-hito commented on test/features/weather/screen/weather_screen_test.dart
> +            // navigatorObservers: [mockNavigatorObserver],
こちらで修正ました
[不要なコメントと改行の削除](https://github.com/oyuno-hito/flutter-training/pull/24/commits/818c0c4bfefbc5400056e1f60605e514494d19a2)

2024-01-30 10:14 UTC, oyuno-hito commented on test/features/weather/screen/weather_screen_test.dart
> +
こちらで修正ました
[不要なコメントと改行の削除](https://github.com/oyuno-hito/flutter-training/pull/24/commits/818c0c4bfefbc5400056e1f60605e514494d19a2)

2024-01-30 10:17 UTC, oyuno-hito commented on test/features/weather/screen/weather_screen_test.dart
> +        await widgetTester.pumpWidget(
こちらで変数名を一括で修正しました。
[a078cb2](https://github.com/oyuno-hito/flutter-training/pull/24/commits/a078cb2e0931ec3efc22a2c3f0306ba8342852d1)

当初の意図としてはモックが必要なテスト(=fetchが実行されるテスト)のみモックを利用することでテスト意図がわかりやすくなることを期待したのですが...
下記コミットの修正だと分岐の可読性がよくないので一律でモックしてしまった方が良さそうに見えますね...レビューいただけると助かります:pray:
[pumpWidgetの汎用関数内でモックするかどうかを柔軟に調整できるように修正](https://github.com/oyuno-hito/flutter-training/pull/24/commits/77be69586584bff28958ee15cb38fbcc3da94e46)

2024-01-30 10:18 UTC, oyuno-hito commented on test/features/weather/screen/weather_screen_test.dart
> +    expect(weatherScreenFinder, findsNothing);
修正漏れでした 🙏 
[Closeボタンのアサーションを修正](https://github.com/oyuno-hito/flutter-training/pull/24/commits/372ee97725ce55b9a19e0d81f9c7ff7ccf0ec68b)

2024-01-30 10:19 UTC, oyuno-hito commented on test/features/weather/screen/weather_screen_test.dart
> +      await widgetTester.pumpAndSettle();
> `Which: means one was found but none were expected`

widgetの描画がうまくいっていないようで`pumpAndSettle`を利用しています
たまたま変えたらうまくいった、程度で具体的になぜ？という部分を理解できていないので根本的な修正をする必要があれば対応します 🙏

2024-01-30 10:20 UTC, oyuno-hito commented
ひとしきり修正と返答をしました。
ディスカッションしたい箇所もあるので再レビュー回させていただいています 🙏

2024-02-01 06:25 UTC, oyuno-hito commented on test/features/weather/screen/weather_screen_test.dart
> +        await widgetTester.pumpWidget(
サジェストのコードをちゃんと読めていませんでした... 🙇 
提案通りの内容で違和感なかったので修正しました！

[eb60cac](https://github.com/oyuno-hito/flutter-training/pull/24/commits/eb60cac4d2b8376ea2f4de0c8d566e0790034dbf)

2024-02-01 06:26 UTC, oyuno-hito commented on test/features/weather/screen/weather_screen_test.dart
> +      await widgetTester.pumpAndSettle();
ペアプロでpumpで問題なくなった理由をご説明いただけたので修正しました！
[e09181a](https://github.com/oyuno-hito/flutter-training/pull/24/commits/e09181af01eff83411342f5fd3c4c95f4577d293)

2024-02-01 06:26 UTC, oyuno-hito commented on test/features/weather/components/error_dialog_test.dart
> +    await widgetTester.pumpAndSettle();
ペアプロでpumpで問題なくなった理由をご説明いただけたので修正しました！
[e09181a](https://github.com/oyuno-hito/flutter-training/pull/24/commits/e09181af01eff83411342f5fd3c4c95f4577d293)

2024-02-01 06:27 UTC, oyuno-hito commented on test/features/weather/components/weather_test.dart
> +        final finder = findSvgImage('assets/sunny.svg');
ペアプロにてパラメタライズドテストにすることでenum値が増えた場合のケースも網羅できるので問題ないとの認識合わせ済み

for, forEach問題についても参考記事を共有いただいている
https://scrapbox.io/dicenull/avoid_function_literals_in_foreach_calls

2024-02-02 01:24 UTC, trm11tkr requested changes
一点タイポを発見したのでそちらだけ修正お願いします！

2024-02-02 01:24 UTC, trm11tkr commented on lib/features/weather/components/degrees.dart
>    static const _defalutValue = '**';
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
細かい点ですが、レビュー漏れてました🙏

```suggestion
  static const _defaultValue = '**';
```

2024-02-02 04:37 UTC, oyuno-hito commented on lib/features/weather/components/degrees.dart
>    static const _defalutValue = '**';
こちらで修正しました 🙏 
[866c349](https://github.com/oyuno-hito/flutter-training/pull/24/commits/866c3494a07b532ed6549c53ecb24e3d4b8f289c)

2024-02-02 05:07 UTC, trm11tkr approved these changes
LGTM です！ご対応いただきありがとうございました！
![LGTM](https://images.lgtmgen.org/27314ed8-d30f-45eb-a2de-7b74ce7095ca)

2024-02-02 05:19 UTC, oyuno-hito commented
レビューありがとうございます！マージします！

2024-02-02 05:19 UTC, merged