Session/11 スレッドブロック
oyuno-hito/flutter-training pull request #25
Opened 2024-02-01 11:23 UTC by oyuno-hito

## 課題

close #12

## 対応箇所

- [x] 使用する API を fetchWeather() から syncFetchWeather() に変更する
- [x] API の処理が戻るまで [CircularProgressIndicator](https://api.flutter.dev/flutter/material/CircularProgressIndicator-class.html) を表示する

- [ ] isolateで扱うべき処理について
  - FYIのため省略
- [x] syncFetchWeather への変更に伴い、ARCHITECTURE.md, テストの修正を行っているか
  - ARCHITECTURE.mdは具体的な変数名を使用していない+同期非同期に関心を持たない記載になっているため

## 動作

| expected | actual(iOS) | actual(android) |
|----------|--------|--------|
| ![image](https://github.com/oyuno-hito/flutter-training/assets/41560259/50b1d93f-e2a7-4feb-b57b-f72d9c851748)      |    ![ios](https://github.com/oyuno-hito/flutter-training/assets/41560259/27daa669-0ff0-4184-afcc-b750aa008a69)| ![android](https://github.com/oyuno-hito/flutter-training/assets/41560259/3f563970-a27e-4e9e-945c-9811bb728c70) |

2024-02-05 01:42 UTC, trm11tkr requested changes
ご対応いただきありがとうございます！
いくつかコメントさせていただきましたのでご確認よろしくお願いします!

2024-02-05 01:42 UTC, trm11tkr commented on lib/features/weather/screen/weather_screen.dart
> +  static const dialogColor = Colors.black54;
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
ダイアログのデフォルトの背景色

2024-02-05 01:42 UTC, trm11tkr commented on lib/features/weather/screen/weather_screen.dart
> +                                },
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
アロー演算子から変更した理由は [discarded_futures](https://dart.dev/lints/discarded_futures) という警告が発生するためでしょうか？
であれば以下のように `unawaited`でラップすると解決できそうです。

```suggestion
                                onPressed: unawaited(
                                  ref
                                      .read(
                                        weatherScreenStateNotifierProvider
                                            .notifier,
                                      )
                                      .fetchWeather(area, date),
                                ),
```

2024-02-05 01:42 UTC, trm11tkr commented on test/features/weather/repository/yumemi_weather_repository_test.dart
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
前回レビューを漏らしていましたが、ファイルの配置場所が間違っていそうです。
`test/features/weather/repository/provider/`配下が適切そうです。

2024-02-05 01:42 UTC, trm11tkr commented on build.yaml
> +            - lib/features/weather/screen/state/*.dart
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
👍

2024-02-05 01:42 UTC, trm11tkr commented on test/features/weather/screen/weather_screen_test.dart
![next-badge](https://img.shields.io/badge/review-next-blueviolet) 
Issue に書かれていないため、対応するかはお任せしますが `CircularProgressIndicator` が表示されていることを検証するとさらに良さそうに思いました。

2024-02-05 06:47 UTC, oyuno-hito commented on lib/features/weather/screen/weather_screen.dart
> +  static const dialogColor = Colors.black54;
忘れやすそうなので修正指摘ではないですがコメント追記しました！
[1bf3556](https://github.com/oyuno-hito/flutter-training/pull/25/commits/1bf3556b63643d8342e79a60b2ac228246c6b8b2)

2024-02-05 07:00 UTC, oyuno-hito commented on test/features/weather/repository/yumemi_weather_repository_test.dart
これって本来はprovider経由でなく直接repositoryを呼び出してテストする方が良かったですかね...？
少なくともこの場合はファイル名も`repository_provider_test`の方が適切になりますでしょうか？

階層だけ一旦修正しています

[6c98dc8](https://github.com/oyuno-hito/flutter-training/pull/25/commits/6c98dc83bbc3bee5d1dafbe9e643d2391a880aaf)

2024-02-05 07:03 UTC, oyuno-hito commented on lib/features/weather/screen/weather_screen.dart
> +                                },
一旦修正コミット積んでいます
[21de27c](https://github.com/oyuno-hito/flutter-training/pull/25/commits/21de27cb6a54404113182825288ed652dc3953a6)

[ask]
今回は呼び出す関数を待って実行したいアクションがないのでunawaitedで問題ないということでしょうか？

今回の設計だとprovider内でstateの更新をしておりonPressedで実行する関数内で待ちたい処理はないですが、実案件も大抵は似た設計になっていたりしますか？

2024-02-05 07:24 UTC, oyuno-hito commented on test/features/weather/screen/weather_screen_test.dart
FEだとテスト思想としてユーザーの体験に近い形でテストを設計する、みたいなものもあるのですが非同期のロード中をテストするのは難しそうですね...

下記記事を参考にするとfetch中はAsyncLoadingになることをモデルのテストで検証できるとよりgoodという感じでしょうか。今回はそこまで踏み込むのは避けておこうと思います
https://qiita.com/Seo-4d696b75/items/b677999b4a82fcda11dd

2024-02-08 08:20 UTC, oyuno-hito commented on test/features/weather/repository/yumemi_weather_repository_test.dart
> これって本来はprovider経由でなく直接repositoryを呼び出してテストする方が良かったですかね...？
こちらに関してはproviderのテストをするのが良いと口頭で確認できたので現在のテストの書き方を維持します！(そうでなくても時間の都合的に変えない方向に倒す腹づもりでした)

ファイルのリネームを実施しました！
[6f46e03](https://github.com/oyuno-hito/flutter-training/pull/25/commits/6f46e03e7c813dfcc2715fa881796b8aad9a9c4f)

2024-02-08 08:21 UTC, oyuno-hito commented on test/features/weather/screen/weather_screen_test.dart
口頭で認識合わせして、やはりwidgetテストとしてはUI操作に近い形でテストする方が良い、という認識で統一したのでcompleterを利用する形でテストを追記しました！
[6af4791](https://github.com/oyuno-hito/flutter-training/pull/25/commits/6af4791685fd073096fcc66152da1855079b454c)

2024-02-08 08:22 UTC, oyuno-hito commented on lib/features/weather/screen/weather_screen.dart
> +                                },
> 今回は呼び出す関数を待って実行したいアクションがないのでunawaitedで問題ないということでしょうか？

Yes. 今回の場合は上記の理由からunawaitedの方が望ましい。

2024-02-08 23:11 UTC, trm11tkr approved these changes
LGTMです！ご対応いただきありがとうございました！

![LGTM](https://images.lgtmgen.org/03bd1352-3abd-42c1-bd7c-4feafb37923c)

2024-02-09 03:56 UTC, merged